services:
  web_oauth:
    build: .
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8888'
    ports:
      - '8888:80'
      - '4443:443'
      - '2222:22'
